### ISSUE TITLE
Name conflict, iwctl is already taken by the iNet wireless daemon

### ISSUE THREAD

**Issue by tomalexander** [InitWare/InitWare#21]
Intel's iNet wireless daemon already is already using `iwctl` as a binary name. Iwd has existed for 7 years, has been public since at least 2017, and is growing in popularity as a faster replacement for wpa_supplicant. As far as I know, iwd is only targeting Linux, but this project is also targeting linux so you're going to hit conflicts.

Man page: https://man.archlinux.org/man/community/iwd/iwctl.1.en
Arch Linux Wiki: https://wiki.archlinux.org/title/Iwd

**Comment by netbsduser** [comment]
How about `svc` for a prefix? That yields `svcctl`, `svcloginctl`, `svcrun`, `svcactivate`, `svcanalyse`, etc.

**Comment by netbsduser** [comment]
The `iw` prefix is now `svc`, so there's no conflict with `iwctl` anymore.
