### ISSUE TITLE
Process tracking with Kernel Queues on BSD platforms

### ISSUE THREAD

**Issue by netbsduser** [InitWare/InitWare#3]
All modern BSD platforms, including macOS, provide the Proc event filter for their Kernel Queues, which allows almost perfect process tracking.

We should do the following to support this:

- integrate a kernel queue into the event loop
- implement a simple CGroups-like abstraction, which we will call for short `PCGroups`, which provides a hierarchy of pseudo-CGroups which can contain PIDs and further PCGroups, and functions to put PIDs in these groups, and to iterate over their members.
- write out all the PCGroups state to the serialisation file, and rewatch all PIDs, for daemon-reexec events. (n.b. slightly racy)
- make fork()'d processes wait for the go-ahead from the manager before they begin to do anything, so we can be sure they are registered with the kernel queue by the parent, and assigned to the appropriate PCGroup.

n.b. In exceptional cases tracking will break down with this mechanism. Either allocation of the note for a forked process may fail in the kernel, or we may fail to allocate our own structures related to the tracking. I don't think there is an easy answer to this problem. The best we can do, probably, is to iterate over every process in the system/belonging to the user (for system or user instances respectively), and try to put it in the right place in the pcgroup hierarchy by reference to its parent PID.

**Comment by JX7P** [comment]
A lot of this is now done as of 8e27fa4. Remaining is:
- iteration functions
- de/serialisation
- maybe forwarding all NOTE_EXITS as SIGCHLD events to the manager, in case of `iwrun` attaching a process to a PTGroup

Then we will be wanting to implement PTGroup-based kills (just overload KILL_CGROUP since overloading the CGroups semantics is our general approach here), and probably some kind of cgls-alike.

**Comment by JX7P** [comment]
I think it's just iteration and PTGroup-based process killing now, plus forwarding SIGCHLD events.
For killing by a PTGroup I think we might need to call into kqueue after a round to check for any newly-forked services.

**Comment by netbsduser** [comment]
First go at killing-by-PTGroup is committed as 17263ea7237e0d3dd10fc5b36f4b2958b19849f9. It does not try to find newly forked services yet because if we called into kevent to update our process lists, then we'd have a load of exit events to dispatch, and I'm not sure if that would play friendly with a service which is already in a transition function. Unfortunately neither CGroups nor PTGroups are actual job management systems, and PTGroups, unlike CGroups, never can be extended in that direction.

**Comment by netbsduser** [comment]
Moving to using a FUSE CGroupFS instead on BSD platforms, therefore this is no longer a concern.
