### ISSUE TITLE
PTGroup as libray

### ISSUE THREAD

**Issue by xxxxxliil** [InitWare/InitWare#38]
If PTGroup can act as a libray, then other service monitoring tools will also benefit from it
To avoid possible licensing issues, it is recommended that PTGroup use a more lenient license, such as MIT

**Comment by netbsduser** [comment]
I've rewritten the PTGroup system as a FUSE filesystem which provides a CGroupFS-compatible filesystem for BSD systems. It will be made a separate project soon with its own repository.

**Comment by netbsduser** [comment]
I've published this at https://github.com/InitWare/CGrpFS under the BSD licence.
