### ISSUE TITLE
Flatpak compatability?

### ISSUE THREAD

**Issue by MonAaraj** [InitWare/InitWare#42]
Hey, this is an awesome project and I really appreciate all the work being done on this. I've just got one question that I'm unsure if this project really plans to deliver on this, does already, or doesn't plan to. Since I've not seen anything by searching, I'll just ask here; does Flatpak work? If not, is it ever planned to work?

**Comment by netbsduser** [comment]
Thanks for your support, glad to hear of it.

InitWare aims to keep providing full compatibility with the major interfaces of systemd, so Flatpak should work fine - maybe just with small patches. If it doesn't work, then I would improve InitWare's systemd compatibility to let it work. I haven't tried it yet myself however.

This is the case for InitWare on Linux. But on BSD platforms there would be other compatibility issues in Flatpak, which I understand uses namespaces and other Linux features which don't all have directly-analogous features in every BSD platform. A wider project to port Flatpak would be necessary there.

**Comment by MonAaraj** [comment]
Ah, yeah, that completely missed my mind in regards to the BSDs, by the time I made this issue; I will be closing this. 

Just if someone stumbles into this, after realising that Flatpak uses some Linux-only features, I tried to research some of the features that Flatpak said it uses that are Linux-only and looked to see if there are any alternatives, and this is as far as I got (just mentioning so that people can know what is specifically needing to be changed):

| Linux            |            BSD               |  
|----------------- | --------------------------- |
|CGroups       | PTGroups, RCTL      |
|bind mounts  | nullfs mounts, bindfs |
|namespaces | jails, bhyve                |
|seccomp       | capsicum                  |

this is not an exhaustive list, though. I didn't bother to read through the source code and see exactly how many features they use, but those are the features that i've seen them mention. There's really only one feature I found that doesn't have an equivalent in the BSDs which is the `keyctl` syscall.
