### ISSUE TITLE
Alternative to using libdbus

### ISSUE THREAD

**Issue by netbsduser** [InitWare/InitWare#6]
The D-Bus C API is an unmitigated monstrosity, and using it directly after having any prior experience with a highly useable messaging system like Objective-C's Distributed Objects, or even just about any other system, is an exercise in misery. Apparently GLib's G-D-Bus is nicer to use, but GLib is an inappropriate dependency for systems software.

Let's put further efforts into something that isn't miserable and depressing to use. JSON-RPC over Unix domain sockets, or even VarLink, is a better option for some basic interfaces, e.g. the CGroups release agent's message. We might also look into whether sd-bus could be ported.

**Comment by unrelentingtech** [comment]
https://github.com/emersion/basu is sd-bus extracted from systemd, and it is ported to FreeBSD. Shouldn't be *too* hard to add other BSDs there.

**Comment by netbsduser** [comment]
I've got sd-bus working on NetBSD now. I think I'll opt to switch over to that.

**Comment by netbsduser** [comment]
New InitWare development branch now uses a pared-down sd-bus instead of libdbus.
